# Generated by Django 4.1.1 on 2022-10-19 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("admin", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Counseler",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("First_Name", models.CharField(max_length=100, unique=True)),
                ("Last_Name", models.CharField(max_length=100, unique=True)),
                ("Subject", models.CharField(max_length=100, unique=True)),
                ("Department", models.CharField(max_length=100, unique=True)),
                ("Mob_no", models.CharField(max_length=100, unique=True)),
                ("Phone_no", models.CharField(max_length=100, unique=True)),
                ("Email", models.EmailField(max_length=254)),
                ("Address", models.CharField(max_length=100, unique=True)),
                ("Country", models.CharField(max_length=200)),
                ("City", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Title", models.CharField(max_length=10)),
                ("First_Name", models.CharField(max_length=100, unique=True)),
                ("Last_Name", models.CharField(max_length=100, unique=True)),
                ("Father_Name", models.CharField(max_length=100, unique=True)),
                ("Email", models.EmailField(max_length=100)),
                ("Major", models.CharField(max_length=50)),
                ("Roll_no", models.CharField(max_length=15, verbose_name="rollno")),
                ("Subject", models.CharField(max_length=100)),
                ("CNIC", models.IntegerField()),
                ("Martial_status", models.CharField(max_length=200)),
                ("DOB", models.DateField(default=django.utils.timezone.now)),
                ("Cell_no", models.CharField(max_length=200)),
                ("Parent_mob", models.IntegerField()),
                ("Gender", models.CharField(max_length=200)),
                ("Admission_year", models.DateField()),
                ("Country", models.CharField(max_length=200)),
                ("City", models.CharField(max_length=200)),
                ("Address", models.CharField(max_length=250)),
                ("Confirm_address", models.CharField(max_length=250)),
                ("Zip_code", models.IntegerField()),
            ],
        ),
    ]
