# Generated by Django 4.1.1 on 2022-10-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminHOD",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("admin", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(old_name="Student", new_name="Students",),
        migrations.DeleteModel(name="Admin",),
    ]
