# Generated by Django 4.1.1 on 2022-10-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edu_app", "0003_rename_adminhod_adminlogin_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="Admission_year", new_name="Admission_date",
        ),
    ]
