# Generated by Django 4.1.1 on 2022-11-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu_app", "0004_rename_admission_year_student_admission_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
