# Generated by Django 4.1.1 on 2022-11-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu_app", "0006_rename_major_student_program"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
