# Generated by Django 4.1.1 on 2022-11-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu_app", "0008_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
