# Generated by Django 4.1.1 on 2022-11-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edu_app", "0010_alter_user_id"),
    ]

    operations = [
        migrations.DeleteModel(name="Adminlogin",),
        migrations.DeleteModel(name="user",),
    ]
