# Generated by Django 4.1.1 on 2022-11-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu_app", "0011_delete_adminlogin_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=200)),
                ("attendance_date", models.DateField()),
                ("session_year", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
