# Generated by Django 4.1.1 on 2022-11-22 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("edu_app", "0012_attendance"),
    ]

    operations = [
        migrations.RemoveField(model_name="attendance", name="updated_at",),
        migrations.AlterField(
            model_name="attendance",
            name="attendance_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="created_at",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="session_year",
            field=models.DateField(null=True),
        ),
    ]
