# Generated by Django 4.1.1 on 2022-11-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu_app", "0015_alter_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
